### ISSUE TITLE
Release 1.0.5

### ISSUE THREAD

**Issue by adam-nielsen** [marconi1992/serverless-offline-lambda#14]
Would it be possible to have an updated release with the latest commits to master?  I'm deploying my code and relying on those changes but it ain't working because they haven't made it into `npm` yet!

**Comment by marconi1992** [comment]
Hi @adam-nielsen, good catch. I'll do it

**Comment by marconi1992** [comment]
Thanks @adam-nielsen , it's done.

**Comment by adam-nielsen** [comment]
Perfect, many thanks for that!
