### ISSUE TITLE
Question: Is it possible to use function environment variables?

### ISSUE THREAD

**Issue by thomas-rw** [marconi1992/serverless-offline-lambda#6]
In my current scenario I have two lambdas. Lambda 1 invokes lambda 2. Serverless offline is loading lambda 1 and sets the environment variables based on the `serverless.yml` file config. Lambda 2 also has environment variables set; however, `process.env` doesn't contain them when lambda 2 is invoked. Lambda 2 doesn't have access to the environment variables set by serverless offline either (example `IS_OFFLINE`). 

Do you think it is possible to load the environment variables from the function and inject IS_OFFLINE when the local Hapi server is spun up? 

Thank you for the great plugin 🎉

**Comment by thomas-rw** [comment]
Hey @marconi1992 - I've been playing around looking for solutions to #5 and this issue. I think I found one. What do you think about moving the `handlers` const from [line 30](https://github.com/marconi1992/serverless-offline-lambda/blob/master/src/index.js#L30) to [line 45](https://github.com/marconi1992/serverless-offline-lambda/blob/master/src/index.js#L45). This ensures the handler is lazy loaded solving #5. It also ensures the environment variables are set by `serverless-offline` when the handler is required.

Let me know what you think! Thanks.

P.S. I'm happy to open a PR if you are okay with this solution.

**Comment by marconi1992** [comment]
@thomas-rw  Regarding the hot reloading support those changes are fine, feel free to submit a PR I'll really appreciate it 😄

**Comment by thomas-rw** [comment]
Excellent! I'll get one open in the next day or two 👍
